spring:
  application:
    name: Tengen
  datasource:
    url: jdbc:h2:~/projects/Tengen/tengendb
    username: user
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 60480000
  minio:
    url: http://localhost:9001
    bucket: tengen-bucket
    access-key: minio-admin
    secret-key: minio-admin
    port: 9000

server:
  port: 8080